tsconfig.json:
  compilerOptions:
    baseUrl: '.'
    rootDir: src
    outDir: dist
    module: commonjs
    target: es2018

    sourceMap: false
    allowJs: false

    moduleResolution: node

    strict: true
    noUnusedLocals: true
    noUnusedParameters: true

    noImplicitReturns: true
    forceConsistentCasingInFileNames: true
    newLine: lf

    removeComments: true

package.json:
  name: kobis
  version: 1.0.0
  author: Xnuk Shuman
  license: BSD-3-Clause

  scripts:
    build: tsc
    run: node ./dist/app.js

  dependencies:
    node-html-parser: ^1.1.16

  devDependencies:
    '@types/node': ^12.7.7
    typescript: ^3.6.3
    prettier: ^1.18.2

.prettierrc.json:
  printWidth: 80
  tabWidth: 4
  useTabs: true
  endOfLine: lf

  semi: false
  trailingComma: all

  singleQuote: true
  quoteProps: as-needed

  bracketSpacing: true
  arrowParens: avoid
